{ created_at: 'Fri Jun 10 11:02:05 +0000 2016',
  id: 741223905948471300,
  id_str: '741223905948471297',
  text: 'PECHUGAS DE POLLO A LA MORUNA\nALBONDIGAS CON TOMATE\nSOLOMILLO A LA NARANJA\n\npostres\nFLAN DE HUEVO\nCONTESSA\nSANDIA\nHELADOS',
  truncated: false,
  entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
  source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: 
   { id: 1972030176,
     id_str: '1972030176',
     name: 'Bar Muriel',
     screen_name: 'bar_muriel',
     location: '',
     description: '',
     url: null,
     entities: { description: [Object] },
     protected: false,
     followers_count: 136,
     friends_count: 16,
     listed_count: 5,
     created_at: 'Sat Oct 19 16:09:09 +0000 2013',
     favourites_count: 15,
     utc_offset: null,
     time_zone: null,
     geo_enabled: false,
     verified: false,
     statuses_count: 1913,
     lang: 'es',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_image_url: 'http://pbs.twimg.com/profile_images/627436271762321408/4G97KrpI_normal.jpg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/627436271762321408/4G97KrpI_normal.jpg',
     profile_link_color: '0084B4',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     has_extended_profile: false,
     default_profile: true,
     default_profile_image: false,
     following: true,
     follow_request_sent: false,
     notifications: false },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  favorited: false,
  retweeted: false,
  lang: 'es' }
